ROADMAP.md

setup build

---

app/layout.tsx
components/GenerationsContainer.tsx
components/PokemonCard.tsx
package-lock.json
package.json

add vercel analytics

---

ROADMAP.md
app/page.tsx
components/Pokedex.tsx
components/PokemonCard.tsx
package-lock.json
package.json

optimize initial render

---

components/PokemonCard.tsx
package-lock.json
package.json
utils/fetchPokemonDataParser.ts

add react loading

---

components/GenerationButton.tsx
components/PokemonCard.tsx

- changed card color to light blue
- changed hover to blue
- changed click to dark blue
- added ease transition when hovering
- made font smaller for text to fit on card
- made text bold to be more readable

CSS changes

---

.github/workflows/playwright.yml
.gitignore
ROADMAP.md
package-lock.json
package.json
playwright.config.ts
tests/Pokedex.spec.ts

setup e2e testing with playwright

---

components/LoadMoreButton.tsx
components/Pokedex.tsx
tests/Pokedex.spec.ts

Update Load More

---

app/globals.css
components/GenerationButton.tsx
components/PokemonCard.tsx

-added border to card
-changed font on pokemon cards

CSS chnages

---

app/page.tsx
components/Pokedex.tsx
hooks/usePokedexHook.tsx

speedy fast and clean up

---

components/PokemonCard.tsx
utils/fetchPokemonDataParser.ts

minor fixes

---

ROADMAP.md
components/LoadMoreButton.tsx
components/Pokedex.tsx
hooks/usePokedexHook.tsx
tests/Pokedex.spec.ts

scroll up button

---

app/layout.tsx
app/page.tsx
app/region/gen-I/page.tsx
app/region/gen-II/page.tsx
app/region/gen-III/page.tsx
app/region/gen-IV/page.tsx
app/region/gen-IX/page.tsx
app/region/gen-V/page.tsx
app/region/gen-VI/page.tsx
app/region/gen-VII/page.tsx
app/region/gen-VIII/page.tsx
components/GenerationButton.tsx
components/GenerationsContainer.tsx
components/Pokedex.tsx
components/Title.tsx
data/pokemonGenerations.js
tests/Pokedex.spec.ts

update pokedex pages

---

ROADMAP.md

update ideas for project

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/playwright.yml
app/api/graphql/route.ts
tests/Pokedex.spec.ts

add new consumer ID

---

app/api/graphql/route.ts
app/backend/page.tsx
app/layout.tsx
components/PokemonChatSupportBox.tsx
graphql/fetchData.ts
graphql/queries/dataQuery.ts
graphql/queries/relatedQuery.ts
playwright.config.ts
tests/Pokedex.spec.ts

add chatbox

---

app/api/graphql/route.ts
components/PokemonChatSupportBox.tsx
graphql/queries/findQuery.ts

update chatbox with find API

---

components/PokemonCard.tsx
components/PokemonCardsContainer.tsx
types/PokemonData.ts
utils/fetchPokemonDataParser.ts

add shiny fix

---

app/page.tsx
components/LoginButton.tsx

created login button component and added the button to  the page.tsx file

Login button

---

app/account/page.tsx
app/api/graphql/route.ts
app/backend/page.tsx
components/PokemonChatSupportBox.tsx
graphql/queries/accountQuery.ts
graphql/queries/dataQuery.ts
graphql/queries/findQuery.ts
graphql/queries/relatedQuery.ts

add account page and query

---

app/layout.tsx
package-lock.json
package.json

add vercel tools

---

app/account/page.tsx
app/api/graphql/route.ts
app/login/page.tsx
components/GenerationsContainer.tsx
components/Providers.tsx
graphql/mutations/loginMutation.ts
tests/Pokedex.spec.ts

login page wiring

---

app/layout.tsx
playwright.config.ts

update worker count

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/playwright.yml

optimize ci caching

---

ROADMAP.md
app/account/page.tsx
app/api/auth/logout/route.ts
app/api/auth/set-cookie/route.ts
app/api/graphql/route.ts
app/login/page.tsx
components/AuthButton.tsx
components/Navigation.tsx
components/PokemonCardsContainer.tsx
components/Providers.tsx
components/ShinyToggle.tsx
contexts/AuthContext.tsx
contexts/ShinyContext.tsx
graphql/fetchData.ts
graphql/queries/accountQuery.ts
middleware.ts
tests/Pokedex.spec.ts

add auth global context

---

components/DisplayCardModal.tsx
utils/fetchPokemonDataParser.ts

display updates

---

app/Signup/page.tsx
app/api/graphql/route.ts
components/AuthButton.tsx
components/Navigation.tsx
contexts/AuthContext.tsx
graphql/mutations/signupMutation.ts
tests/Pokedex.spec.ts

signup flow

---

components/PokemonCard.tsx
components/PokemonCardsContainer.tsx

changed color and format of cards

card layout improvements

---

app/globals.css
components/PokemonCard.tsx

changed background color
erased image
changed title color

changed background
